// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Models;

namespace WebApplication.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181111021345_W")]
    partial class W
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication.Models.Post", b =>
                {
                    b.Property<int>("PostKey")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PostMessage")
                        .HasMaxLength(300);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(127);

                    b.HasKey("PostKey");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("WebApplication.Models.User", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("Password")
                        .HasMaxLength(14);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("UserName")
                        .HasMaxLength(127);

                    b.HasKey("Key");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasName("Key");

                    b.ToTable("Users");

                    b.HasData(
                        new { Key = 1, Password = "Password123!", UserName = "Customer1@email1.com" },
                        new { Key = 2, Password = "Password123!", UserName = "Customer1@email2.com" },
                        new { Key = 3, Password = "Password123!", UserName = "Customer1@email3.com" },
                        new { Key = 4, Password = "Password123!", UserName = "Customer1@email4.com" },
                        new { Key = 5, Password = "Password123!", UserName = "Customer1@email5.com" },
                        new { Key = 6, Password = "Password123!", UserName = "Member1@email.com" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
